language: ruby
rvm:
- 2.5.1
cache: bundler
install: bundle install
script: jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "Jwaz4BMQtk9IQRY/oENxTiTAhYGv7P8s8Y+HgulYJ+k/0pgCSchWyiA/S3wctXBR1EhLjzKcZDBym84Z+z/0i9wFhjCdVlVcwahYDKE1kRijFo9cN4lqKIFtbCVUUQvfT74DYHZttPM89R+B1A01BaFebEzo8GTsB1dn9/0+ejnvm1XkEFNRtDEerJmaGgzFELHKp1/ClMyxat1wAkRuR2I+ai+4vNB0oqX/Fe4i18NeekiVStmt0KvASDe29fyJLh5XSBRDP5LWOEcZLCNFq+0pzDRk67oNLrH5eYHxjA3B0y1FMFuiGgaMUGUhWtbZwRuCl620BCP5A/lXYO98s937zSGYyTFxlAr/3TrXOa8DLnExQXgcn7wKH5WN45GvcOppvO/gz/Zxgwwp4TD9cYq7R1LBA8wtoctj3JKrxejFlEBc7PaA3+4hmnPCu4PF7aHIVPlCq0hIUnEaxPum+A8y90fM/Ntx1V5+l76WaCZGaW8bt3bsNLG81C5lG1jRJuARc1kzJTCpoR65behJBIZovuv+qdzTkCe3kyszZPscbDX6TJVTEaoH9248J32eghQqpha+USTRUIlY6o2bm0Hu6DaxCg1oDD5pFO/6vmH1FzGAbJUdb+OjZrAM4gMpMN6Ti2qWeE8Ve1vd3qGby2eVR3jQpa4yAHQE13Tzdgg="
  on:
    branch: master
env:
 - JEKYLL_ENV=production
